# Generated by Django 4.0 on 2022-04-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
    ]
