# Generated by Django 4.0 on 2022-05-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_remove_contactus_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us Message', 'verbose_name_plural': 'Contact Us Messages'},
        ),
    ]
