# Generated by Django 4.0 on 2022-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyaratcontactcompany',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Tax ID'),
        ),
    ]
