# Generated by Django 4.0 on 2022-03-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('checkoutdetails', '0003_booking_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payment.paymenttransaction', verbose_name='Payment Transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN_PROGRESS'), (2, 'APPROVED'), (3, 'EXPIRED'), (4, 'PAYED')], default=0, verbose_name='Status'),
        ),
    ]
