# Generated by Django 4.0 on 2022-03-18 07:35

from django.db import migrations

from location.models import ServiceProvider


def create_dhl_service_provider(apps, schema_editor):
    name = 'DHL'
    ServiceProvider.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dhl_service_provider)
    ]
