# Generated by Django 4.0 on 2022-03-18 08:01

from django.db import migrations


def assign_user_to_dhl_service_provider(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    ServiceProvider = apps.get_model('location', 'ServiceProvider')

    ServiceProvider.objects.filter(name="DHL").update(user=CustomUser.objects.filter(username="DHL").first())


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20220318_0735'),
        ('users', '0014_auto_20220318_0742')
    ]

    operations = [
        migrations.RunPython(assign_user_to_dhl_service_provider)
    ]
