# Generated by Django 4.0 on 2022-03-18 08:23

from django.db import migrations


def create_aramex_service_provider(apps, schema_editor):
    name='aramex'
    ServiceProvider = apps.get_model('location', 'ServiceProvider')
    ServiceProvider.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220318_0801'),
    ]

    operations = [
        migrations.RunPython(create_aramex_service_provider)
    ]
