# Generated by Django 4.0 on 2022-03-18 08:30

from django.db import migrations


def assign_user_to_aramex_service_provider(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    ServiceProvider = apps.get_model('location', 'ServiceProvider')

    ServiceProvider.objects.filter(name="aramex").update(user=CustomUser.objects.filter(username="aramex").first())


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20220318_0823'),
        ('users', '0013_add_aramex_user')
    ]

    operations = [
        migrations.RunPython(assign_user_to_aramex_service_provider)
    ]
