# Generated by Django 4.0 on 2022-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20220318_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='citycountryserviceprovider',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='countrycode',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
