# Generated by Django 4.0 on 2022-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_citycountryserviceprovider_post_code1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
    ]
