# Generated by Django 4.0 on 2022-05-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0026_order_item_description_order_need_customs_brokerage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortToPortCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Code')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_to_port_charges', to='orders.quotation', verbose_name='Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OriginCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Code')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_charges', to='orders.quotation', verbose_name='Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OriginAddressCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Code')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_address_charges', to='orders.quotation', verbose_name='Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinationCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Code')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_charges', to='orders.quotation', verbose_name='Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinationAddressCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Code')),
                ('fee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fee Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('units', models.IntegerField(default=1, verbose_name='Units')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unit Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_address_charges', to='orders.quotation', verbose_name='Quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
