# Generated by Django 4.0 on 2022-04-05 08:42

from django.db import migrations
from django.conf import settings


def create_usd_currency(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")
    CurrencyRate = apps.get_model("currency", "CurrencyRate")

    currency_usd = Currency.objects.create(name=settings.USD_CURRENCY_NAME, main=True)
    CurrencyRate.objects.create(rate=settings.USD_CURRENCY_RATE, currency=currency_usd)

    currency_eur = Currency.objects.create(name=settings.EUR_CURRENCY_NAME)
    CurrencyRate.objects.create(rate=settings.EUR_CURRENCY_RATE, currency=currency_eur)

    currency_sar = Currency.objects.create(name=settings.SAR_CURRENCY_NAME)
    CurrencyRate.objects.create(rate=settings.SAR_CURRENCY_RATE, currency=currency_sar)


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_rate_currency_main_and_more'),
    ]

    operations = [
        migrations.RunPython(create_usd_currency)
    ]
