# Generated by Django 4.0 on 2022-01-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_company_description_alter_company_tax_id_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cargo_ready_date', models.DateField(verbose_name='Cargo ready date')),
                ('transport_mode', models.IntegerField(choices=[(1, 'Sea freight'), (2, 'Land'), (3, 'Air cargo')], db_index=True, default=2, verbose_name='Preferred transport mode')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.container')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.package')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.parcel')),
                ('shipment_destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_destination', to='users.address', verbose_name='shipment_destination')),
                ('shipment_origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_origin', to='users.address', verbose_name='shipment_origin')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
    ]
