# Generated by Django 4.0 on 2022-01-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_company_description_alter_company_tax_id_and_more'),
        ('orders', '0002_alter_order_container_alter_order_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Quote'), (2, 'Request'), (3, 'Checkout')], db_index=True, default=1, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_destination', to='users.address', verbose_name='shipment destination'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_origin', to='users.address', verbose_name='shipment origin'),
        ),
    ]
