# Generated by Django 4.0 on 2022-01-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status_alter_order_shipment_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='container',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parcel',
        ),
    ]
