# Generated by Django 4.0 on 2022-01-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_company_description_alter_company_tax_id_and_more'),
        ('orders', '0005_order_archived_order_owner_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='price',
        ),
        migrations.AddField(
            model_name='request',
            name='currency',
            field=models.IntegerField(choices=[(1, 'USD')], default=1, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='request',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated time of arrival'),
        ),
        migrations.AddField(
            model_name='request',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total cost'),
        ),
        migrations.AlterField(
            model_name='request',
            name='carrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Quote'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(verbose_name='Text')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Owner')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.request', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
