# Generated by Django 4.0 on 2022-01-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_company_logo'),
        ('orders', '0006_remove_request_price_request_currency_request_eta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Carrier'),
        ),
    ]
