# Generated by Django 4.0 on 2022-01-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_request_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='valid_till_date',
            field=models.DateField(blank=True, null=True, verbose_name='Valid till date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='orders.order', verbose_name='Quote'),
        ),
    ]
