# Generated by Django 4.0 on 2022-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_request_valid_till_date_alter_request_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Expired')], default=1, verbose_name='Status'),
        ),
    ]
