# Generated by Django 4.0 on 2022-01-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_request_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='archived',
        ),
        migrations.AddField(
            model_name='order',
            name='unit_system',
            field=models.IntegerField(choices=[(1, 'Metric system'), (2, 'Imperial system')], default=1, verbose_name='System of Units'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Quote'), (2, 'Request'), (3, 'Checkout'), (4, 'In progress'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Archieved')], db_index=True, default=1, verbose_name='Order status'),
        ),
    ]
