# Generated by Django 4.0 on 2022-01-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
        ('orders', '0011_order_description_alter_note_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Quotation',
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='request',
        ),
        migrations.AddField(
            model_name='note',
            name='quotation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.quotation', verbose_name='Quotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Request'), (2, 'Quote'), (3, 'Checkout'), (4, 'In progress'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Archieved')], db_index=True, default=2, verbose_name='Order status'),
        ),
    ]
