# Generated by Django 4.0 on 2022-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_request_quotation_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Request'), (2, 'Quote'), (3, 'Checkout'), (4, 'In progress'), (5, 'Shipped'), (6, 'Delivered'), (7, 'Archieved')], db_index=True, default=1, verbose_name='Order status'),
        ),
    ]
