# Generated by Django 4.0 on 2022-01-27 08:31

from django.db import migrations, models
import django.db.models.deletion
import utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_role'),
        ('orders', '0015_alter_order_description_alter_quotation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consignee', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveryman', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rates_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.media.file_path, verbose_name='File rates'),
        ),
    ]
