# Generated by Django 4.0 on 2022-01-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_role'),
        ('orders', '0016_order_consignee_order_consignor_order_deliveryman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Consignee', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignor', to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveryman', to='users.customuser'),
        ),
    ]
