# Generated by Django 4.0 on 2022-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_consignee_alter_order_consignor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Approved'), (3, 'Expired')], default=1, verbose_name='Status'),
        ),
    ]
