# Generated by Django 4.0 on 2022-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_win_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Approved'), (3, 'Expired'), (4, 'Payed')], default=1, verbose_name='Status'),
        ),
    ]
