# Generated by Django 4.0 on 2022-03-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutdetails', '0002_deyaratcontactcompany_tax_id'),
        ('orders', '0021_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='checkoutdetails.deyaratcontactcompany'),
        ),
    ]
