# Generated by Django 4.0 on 2022-03-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20220318_0830'),
        ('orders', '0021_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_orders', to='location.citycountryserviceprovider'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_orders', to='location.citycountryserviceprovider'),
        ),
    ]
