# Generated by Django 4.0 on 2022-03-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_citycountryserviceprovider_active_countrycode_active'),
        ('orders', '0022_order_destination_city_order_origin_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_orders', to='location.citycountryserviceprovider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_orders', to='location.citycountryserviceprovider'),
        ),
    ]
