# Generated by Django 4.0 on 2022-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_company_billing_address'),
        ('orders', '0023_alter_order_destination_city_alter_order_origin_city'),
    ]

    operations = [
    ]
