# Generated by Django 4.0 on 2022-03-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220318_0742'),
        ('orders', '0024_merge_20220328_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_destination', to='users.address', verbose_name='shipment destination'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_origin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_origin', to='users.address', verbose_name='shipment origin'),
        ),
    ]
