# Generated by Django 4.0 on 2022-05-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_shipment_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.TextField(blank=True, null=True, verbose_name='Item Description'),
        ),
        migrations.AddField(
            model_name='order',
            name='need_customs_brokerage',
            field=models.BooleanField(default=False, verbose_name='Need Customs Brokerage'),
        ),
        migrations.AddField(
            model_name='order',
            name='need_insurance',
            field=models.BooleanField(default=False, verbose_name='Need Insurance'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Shipment Value'),
        ),
    ]
