# Generated by Django 4.0 on 2022-06-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_item_description_order_need_customs_brokerage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
