# Generated by Django 4.0 on 2022-01-05 10:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Shipper')], db_index=True, default=1, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Request for Vendor'), (3, 'Vendor')], db_index=True, default=1, verbose_name='Role'),
        ),
    ]
