# Generated by Django 4.0 on 2022-01-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Shipper'), (2, 'Forwader')], db_index=True, default=2, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Request for Carrier'), (3, 'Carrier')], db_index=True, default=1, verbose_name='Role'),
        ),
    ]
