# Generated by Django 4.0 on 2022-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Website'),
        ),
    ]
