# Generated by Django 4.0 on 2022-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_company_description_alter_company_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shipment',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Shipment address'),
        ),
    ]
