# Generated by Django 4.0 on 2022-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Website'),
        ),
    ]
