# Generated by Django 4.0 on 2022-01-17 07:35

from django.db import migrations, models
import utils.media


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_company_description_alter_company_tax_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=utils.media.logo_path, verbose_name='Logotype'),
        ),
    ]
