# Generated by Django 4.0 on 2022-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Unverified Carrier'), (3, 'Verified Carrier'), (4, 'Consignor'), (5, 'Deliveryman'), (6, 'Consignee')], db_index=True, default=1, verbose_name='Role'),
        ),
    ]
