# Generated by Django 4.0 on 2022-03-18 07:42
import os

from django.db import migrations
from django.utils import timezone

from users.models import CustomUser


def create_dhl_user(apps, schema_editor):

    dhl_user = CustomUser(
        is_active=True,
        is_superuser=True,
        is_staff=True,
        username="DHL",
        last_login=timezone.now(),
        email="dhl@mail.com",
        role=3,
        first_name="DHL",
        last_name="we move the world"
    )
    dhl_user.set_password(os.environ.get('DHL_PASSWORD'))
    dhl_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_aramex_user'),
    ]

    operations = [
        migrations.RunPython(create_dhl_user)
    ]
