# Generated by Django 4.0 on 2022-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('container_type', models.IntegerField(choices=[(1, '20 Standart'), (2, '40 Standart')], db_index=True, default=1, verbose_name='Container type')),
                ('cross_weight', models.FloatField(verbose_name='Cross weight')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('overweight', models.BooleanField(default=False, verbose_name='Overweight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('package_type', models.IntegerField(choices=[(1, 'Box'), (2, 'Pallet'), (3, 'Load')], db_index=True, default=1, verbose_name='Package type')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='Length')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('stackable', models.BooleanField(default=False, verbose_name='Stackable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('parcel_type', models.IntegerField(choices=[(1, 'Envelope'), (2, 'Standart Flyer'), (3, 'Large Flyer')], db_index=True, default=1, verbose_name='Parcel type')),
                ('weight', models.FloatField(verbose_name='Weight')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
