# Generated by Django 4.0 on 2022-01-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_archived_order_owner_alter_order_status_and_more'),
        ('products', '0003_package_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='package',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='orders.order'),
        ),
    ]
